### ISSUE TITLE
hw scroll code example?

### ISSUE THREAD

**Issue by ezeeetm** [timotet/SSD1306#2]
I saw you implemented hardware scroll per thread here: https://forum.micropython.org/viewtopic.php?t=2336

Could you maybe include a short working code snippet in the readme.md that shows how to make scrolling work?

Thanks.

**Comment by timotet** [comment]
Hi, The second page of the post gives an example. Here [https://forum.micropython.org/viewtopic.php?f=16&t=2336&sid=61714533162b73348a89552ca601a2a4&start=10](url).

I will add it to the readme.
thanks
